### ISSUE TITLE
crashes on server load

### ISSUE THREAD

**Issue by ghost** [CrafterKina/Pipes#19]
using forge 2214 using game 1.11.2
error is 
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pipes (jp.crafterkina.pipes)
Caused by: java.lang.NoClassDefFoundError: jp/crafterkina/pipes/api/render/ISpecialRenderer`

**Comment by CrafterKina** [comment]
Fixed in 1.1.0.5.
Thanks for reporting.
