### ISSUE TITLE
[1.11] Placing down pipe crashes client over 200 blocks away

### ISSUE THREAD

**Issue by shortybsd** [CrafterKina/Pipes#20]
MC version 1.11
Forge 2199
Pipes version 1.11-1.1.0.5

Placing down pipes for some reason crashes a client really far away. NPE, might need an if check to see if other clients are in range.
http://pastebin.com/UEPhC8Q4

**Comment by CrafterKina** [comment]
Thank you for reporting.
The crash could not be reproduced, so I need to know some information to solve it.

- Maybe you're in multi-play. If you're in single-play, does it occur?
- Does it happen even if "Pipes" mod only installed?
- Was the pipe placed by hand?
- Other. Such as the steps to reproduce.

**Comment by shortybsd** [comment]
Multiplayer, hence the trying to update a client not in range for rendering the pipe at last hence the crash. I have not tested the mod without all other mods. You need an if statement for checking if other players are in range before giving them updates for when they are not in range. I've seen that same crash from other mods a bit due to the same exact issue. Yes sir, the pipe was placed by hand. I can crash anyone on the server when I place pipes to Forestry's multifarm lol. I removed the mod for now.

**Comment by CrafterKina** [comment]
Looking at past crashes, I think that this solution is the best.
Thanks again.

**EDIT**
Revised version ([1.1.0.6](https://github.com/CrafterKina/Pipes/releases/tag/1.11-1.1.0.6)) released.
