### ISSUE TITLE
Add support for Forestry machines

### ISSUE THREAD

**Issue by ghost** [CrafterKina/Pipes#21]
For liquids. should be planned

**Comment by CrafterKina** [comment]
Is your issue [this](https://github.com/CrafterKina/Pipes/issues/20#issuecomment-272986682)?
> I can crash anyone on the server when I place pipes to Forestry's multifarm

If so, this issue is totally different from #20 .
Could you send me the crash report?

**Comment by ghost** [comment]
it's not an issue, it's an important advice just like your other 2 "issues" :)

**Comment by CrafterKina** [comment]
Even working with Forestry, pipe insertion and extraction functions can be used. 
What kind of support do you need for Forestry machines?

**Comment by ghost** [comment]
i need fluid transport, but i couldn't see fluid pipes in your mod. are there any? or there is a different way to make fluid transport?

**Comment by CrafterKina** [comment]
It is planned in #14 .
