### ISSUE TITLE
Multiplayer - Second player crashed MC Client (1.11.2) - Video

### ISSUE THREAD

**Issue by Umiyaki** [CrafterKina/Pipes#22]
minecraft 1.11.2
forge-1.11.2-13.20.0.2216
pipes mod 1.11-1.1.0.6
own server version "forge-1.11.2-13.20.0.2216-universal"

For test only one mod (Pipes) and default resourcepack.

The second player see white texture and then crashes his MC client.  The player who builds sees texture fine. 
Players who crashes client must look at the pipe. If the tube does not see, his MC client does not crash.

Video with crash MS client
https://youtu.be/JbrHnqfNnBY

Crash log
https://justpaste.it/12ie8

**Comment by CrafterKina** [comment]
Thank you for the report!
It is fixed in next revision.
