### ISSUE TITLE
Server crashes after using color tubes (white) 1.11.2

### ISSUE THREAD

**Issue by Umiyaki** [CrafterKina/Pipes#23]
minecraft 1.11.2
forge-1.11.2-13.20.0.2216
Pipes-1.11-1.1.0.7
own server version "forge-1.11.2-13.20.0.2216-universal"

Crash log:
https://justpaste.it/12jhz

Report from server console
https://justpaste.it/12ji4

**Comment by CrafterKina** [comment]
Thank you very much for the report. It is difficult to debug in multi-play...
In 1.1.0.8 this kind of problem probably all resolved.

**Comment by Umiyaki** [comment]
You're welcome. Send report is not a problem. I thank you for the mod.


Dne 18.01.2017 v 18:45 Kina napsal(a):
