### ISSUE TITLE
Add Destroyer and Filter Pipes

### ISSUE THREAD

**Issue by ghost** [CrafterKina/Pipes#24]
Destroyer pipes that destroy the coming item/fluid
for example destroyer fluid connected to a fluid generator machine output, it will take all fluid.
another example that connected to end of the pipes that connected to chest (items coming from) and it destroys all the items.
Should be a scheduled feature :) Friendly advice, you can close it if you don't want to do it.

**Comment by CrafterKina** [comment]
In a future version, "Destroyer" processor will be added. The name may change.
I basically want to implement the function that existed in the past transportation system mod.
Thanks for your suggestion.

**Comment by ghost** [comment]
ah yes that would be fine too. thanks a lot =) 
and i have another suggestion; please add filters. i'm sure you got what i mean. filters for items and fluids too. thanks :)

**Comment by CrafterKina** [comment]
Do you mean filters for branching, extraction, or insertion?
I am planning to add at least a filter at branching.

**Comment by ghost** [comment]
it's like branching, just lets me decide that which item go to which pipe. for example, we have chest1 that contains diamond, gold bar and iron. we connected it a pipe, and we placed the filter pipe to the pipe connection. and we placed 3 more chests; and we want to seperate the diamond, iron bar and gold bars into the 3 chests.

**Comment by StevenGann** [comment]
I'd like to propose "Disposal" in place of "Destroyer".

As for filters, perhaps if when you attach the processor to a pipe an inventory would appear and you place a sample of each item that the filter should accept?
An inverse filter where you specify items to block would be nice.

Back before Bukkit died, I used a plugin called CraftBook as a server-side implementation of pipes and sorters, and have been looking for a single-player mod to recreate that functionality. A filter and inverse filter would go a long way to achieving that.

**Comment by CrafterKina** [comment]
Close for ease of management. This Issue contains two suggestions.
Project cards: https://github.com/CrafterKina/Pipes/projects/1#card-1486710, https://github.com/CrafterKina/Pipes/projects/1#card-1486697
