### ISSUE TITLE
When breaking higher tier pipes they become stick tier

### ISSUE THREAD

**Issue by Kriptikz** [CrafterKina/Pipes#25]
Mod Version: 1.11-1.1.0.8

(Ex.) Take diamond pipe, place it, then break it. Your previously diamond tier pipe is now stick tier. 
This happens with cobblestone, iron, gold, or diamond pipe.

**Comment by CrafterKina** [comment]
Thanks for reporting!
Only because the color was incorrect, it did not become a pipe of stick so you can play on the world you played in 1.1.0.8 or before.

**Comment by Kriptikz** [comment]
Sorry, this doesn't seem to have fixed the problem. The pipes look better in JEI, in inventory, and when holding, but I don't think they render the different tiers in the world.
Back to my example I take a diamond pipe in my inventory and hover over it and press R (JEI Show Recipe) and it shows correct diamond recipe. I then place it, break it and pick it up. This doesn't put the pipe back into my diamond pipe stack in my inventory. It makes a new stack, or if I have stick tier pipes it puts it in that stack and when I press R to show the recipe it shows stick tier. It also goes from rendering the nice diamond tier in my inventory to rendering as stick tier in my inventory after I brake it and pick it up.

**Comment by CrafterKina** [comment]
I didn't do enough tests ... I'm sorry.
This time it was fixed. Sorry about the expensive pipe you put.
