### ISSUE TITLE
Add Hose Pipe(Fluid)

### ISSUE THREAD

**Issue by ghost** [CrafterKina/Pipes#28]
Can you make a thing like this? Let me explain what it is. (friendly advice-question)
I want to place a hose in sea(under of water) And i connect it to a tank, however, i will get infinite water from that. Okay we can get infinite water with 2x2 placement but i want it realistic. Can you do this? It should be easy.

**Comment by CrafterKina** [comment]
Well... Is it like a pump? If so, I might implement it as a processor. If I have room to do it. Behavior like a pump is a bit difficult.

**Comment by ghost** [comment]
yes like a pump, it will consume the water around it. or upward of it... etc.

**Comment by ghost** [comment]
it will like break water block or break liquid blocks from world and give them to me from the other side of fluid pipe connection

**Comment by StevenGann** [comment]
It's not the "realistic" behavior @kenijey is describing, but CraftBook had a pump that worked by destroying a water or lava source block below itself and adding it to the pipe. It could certainly be used over a 2x2 infinite water source, but I always took the time to build pumps over natural lakes.

**Comment by ghost** [comment]
getting water from sea is more realistic than getting it from 2x2 stupid thing

**Comment by StevenGann** [comment]
@kenijey I agree, but from my understanding of Minecraft's water mechanics there's no simple way of identifying a large body of water vs. a small pool. I'm not very familiar with Forge but from my experience with Bukkit the closest you'd likely get would be an iterative search of adjacent water source blocks to see if it meets some definition of a large body of water.

And then, what if the body of water is too small? With the hose simply not function? 

Spitballing a bit here. Suppose there was a sort of hose reel block that when placed would appear to lower a hose down until it hits a solid block. Every time the hose produces a unit of water, the highest 9 source blocks below the reel are deleted. If the water source is too small to refill those sources quickly, the next lower sources will be deleted also, and so on until the pool is drained.

**Comment by ghost** [comment]
okay, but i don't want to drain the sea. i will just get the water from there. all i want is being realistic. i will not go into the sea and sight (hey what is going on here which water block are breaking hey heyyyy nooo!) it's system. all i do is "i am getting water from the sea". and in sea, water is infinite, then breaking 1 block or water like a **sponge**, it will work all the time... ofc draining the pool is impossible because of the minecraft's water system. it is not realistic. you can get wet everywhere with 1 block water. and it is infinite until you get it with a bucket or placing a block on it. it is really bad...
did you play starbound? if you did, you will remember the water system in that game. it is really really realistic. i love that physics&dynamics system in that game. 
however, we are playing minecraft...

**Comment by CrafterKina** [comment]
If you are asking for such a realistic pump, it is not a category of this Mod. Because this is a "Pipes" mod. However, as I said before, I may add it as a processor if it is simple.
