### ISSUE TITLE
[Suggestion] Name change

### ISSUE THREAD

**Issue by Greg-21** [CrafterKina/Pipes#40]
Hello. Have you thought about name change of this modification? The existing one is OK, but it looks like working name. It's not unique. This is like a company that produces fridges was called "fridge" or florist called "flower", etc. I have no idea for a new name. The only one that comes to my head is "Simple Pipes" (or "SimplePipes"), but it is bad too, and only refers if this mod has got only pipes and pipe-related things (such as a tank) in the future.

**Comment by CrafterKina** [comment]
What if it were an acronym? like this: **P**ipes **I**s **P**owerfully **E**ffective transportation **S**ystem
...Changing its name is not attractive to me. I think that such naming is not so rare. For example, Chisel, Iron chests, chest transporter, and so on.

**Comment by Greg-21** [comment]
I didn't think that "Pipes" can be an acronym. Now, when I know that, this name looks more interesting. So if you don't want to change the name of this mod, you can just close this issue.

EDIT: I have just closed this issue.
